// Re-export shared openssl_dynlib into package quic so existing g_os.* call sites work.
// Single process-wide OpenSSL load lives in openssl_dynlib.
package quic

import od "../openssl_dynlib"

// --- types / constants ---
Os :: od.Os
Os_Error :: od.Os_Error
OSSL_PARAM :: od.OSSL_PARAM
OSSL_DISPATCH :: od.OSSL_DISPATCH

OSSL_FUNC_SSL_QUIC_TLS_CRYPTO_SEND :: od.OSSL_FUNC_SSL_QUIC_TLS_CRYPTO_SEND
OSSL_FUNC_SSL_QUIC_TLS_CRYPTO_RECV_RCD :: od.OSSL_FUNC_SSL_QUIC_TLS_CRYPTO_RECV_RCD
OSSL_FUNC_SSL_QUIC_TLS_CRYPTO_RELEASE_RCD :: od.OSSL_FUNC_SSL_QUIC_TLS_CRYPTO_RELEASE_RCD
OSSL_FUNC_SSL_QUIC_TLS_YIELD_SECRET :: od.OSSL_FUNC_SSL_QUIC_TLS_YIELD_SECRET
OSSL_FUNC_SSL_QUIC_TLS_GOT_TRANSPORT_PARAMS :: od.OSSL_FUNC_SSL_QUIC_TLS_GOT_TRANSPORT_PARAMS
OSSL_FUNC_SSL_QUIC_TLS_ALERT :: od.OSSL_FUNC_SSL_QUIC_TLS_ALERT

OSSL_RECORD_PROTECTION_LEVEL_NONE :: od.OSSL_RECORD_PROTECTION_LEVEL_NONE
OSSL_RECORD_PROTECTION_LEVEL_EARLY :: od.OSSL_RECORD_PROTECTION_LEVEL_EARLY
OSSL_RECORD_PROTECTION_LEVEL_HANDSHAKE :: od.OSSL_RECORD_PROTECTION_LEVEL_HANDSHAKE
OSSL_RECORD_PROTECTION_LEVEL_APPLICATION :: od.OSSL_RECORD_PROTECTION_LEVEL_APPLICATION

TLS1_3_VERSION :: od.TLS1_3_VERSION
TLS1_2_VERSION :: od.TLS1_2_VERSION

SSL_VERIFY_NONE :: od.SSL_VERIFY_NONE
SSL_VERIFY_PEER :: od.SSL_VERIFY_PEER

SSL_ERROR_NONE :: od.SSL_ERROR_NONE
SSL_ERROR_SSL :: od.SSL_ERROR_SSL
SSL_ERROR_WANT_READ :: od.SSL_ERROR_WANT_READ
SSL_ERROR_WANT_WRITE :: od.SSL_ERROR_WANT_WRITE
SSL_ERROR_SYSCALL :: od.SSL_ERROR_SYSCALL
SSL_ERROR_ZERO_RETURN :: od.SSL_ERROR_ZERO_RETURN

SSL_TLSEXT_ERR_OK :: od.SSL_TLSEXT_ERR_OK
SSL_TLSEXT_ERR_NOACK :: od.SSL_TLSEXT_ERR_NOACK

EVP_CTRL_AEAD_SET_IVLEN :: od.EVP_CTRL_AEAD_SET_IVLEN
EVP_CTRL_AEAD_GET_TAG :: od.EVP_CTRL_AEAD_GET_TAG
EVP_CTRL_AEAD_SET_TAG :: od.EVP_CTRL_AEAD_SET_TAG

EVP_KDF_HKDF_MODE_EXTRACT_ONLY :: od.EVP_KDF_HKDF_MODE_EXTRACT_ONLY
EVP_KDF_HKDF_MODE_EXPAND_ONLY :: od.EVP_KDF_HKDF_MODE_EXPAND_ONLY

SSL_CTRL_SET_TLSEXT_HOSTNAME :: od.SSL_CTRL_SET_TLSEXT_HOSTNAME
SSL_CTRL_SET_MIN_PROTO_VERSION :: od.SSL_CTRL_SET_MIN_PROTO_VERSION
SSL_CTRL_SET_MAX_PROTO_VERSION :: od.SSL_CTRL_SET_MAX_PROTO_VERSION
SSL_CTRL_SET_GROUPS_LIST :: od.SSL_CTRL_SET_GROUPS_LIST
SSL_CTRL_SET_SESS_CACHE_MODE :: od.SSL_CTRL_SET_SESS_CACHE_MODE
SSL_CTRL_SET_SIGALGS_LIST :: od.SSL_CTRL_SET_SIGALGS_LIST
SSL_SESS_CACHE_OFF :: od.SSL_SESS_CACHE_OFF
TLSEXT_NAMETYPE_host_name :: od.TLSEXT_NAMETYPE_host_name

OSSL_PARAM_INTEGER :: od.OSSL_PARAM_INTEGER
OSSL_PARAM_UTF8_STRING :: od.OSSL_PARAM_UTF8_STRING
OSSL_PARAM_OCTET_STRING :: od.OSSL_PARAM_OCTET_STRING

OPENSSL_VERSION_MIN_3_5 :: od.OPENSSL_VERSION_MIN_3_5

// Shared process Os (pointer — same storage as openssl_dynlib.g_os).
g_os := &od.g_os

os_init :: proc() -> Os_Error {
	return od.os_init()
}

os_ensure :: proc() -> bool {
	return od.os_ensure()
}

ossl_param_int :: od.ossl_param_int
ossl_param_utf8 :: od.ossl_param_utf8
ossl_param_octet :: od.ossl_param_octet
ossl_param_end :: od.ossl_param_end
os_cipher_ctx_new :: od.os_cipher_ctx_new
SSL_CTX_set_min_proto_version :: od.SSL_CTX_set_min_proto_version
SSL_CTX_set_max_proto_version :: od.SSL_CTX_set_max_proto_version
SSL_set_tlsext_host_name :: od.SSL_set_tlsext_host_name
SSL_CTX_set_groups_list :: od.SSL_CTX_set_groups_list
ssl_ctx_apply_lean_tls13 :: od.ssl_ctx_apply_lean_tls13
