[package]
name = "ntex-empty-ok"
version = "0.1.0"
edition = "2021"

[target.'cfg(target_os = "linux")'.dependencies]
ntex = { version = "2", default-features = false, features = ["neon-uring"] }

[target.'cfg(not(target_os = "linux"))'.dependencies]
ntex = { version = "2", default-features = false, features = ["tokio"] }
